// beers for shop
export const beers = [
    {
        name: "Isekai delivery service",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus purus in auctor tempor. Sed feugiat lacinia commodo. Donec aliquet tempor felis ac suscipit. Nulla euismod varius nisi, vel pharetra lacus aliquet sed. Fusce luctus, ante sed luctus pharetra, nunc velit vulputate nisi, eget posuere felis metus quis elit. Praesent sed elit est.",
        images: ["images/beer.jpg", "images/neko.webp", "images/beer.jpg"],
        alcohol: "9%",
        price: 10.00,
        discount: 10,
        color_scheme: "white",
        batch_number: 1,
        link: "isekai_delivery_service",
        stock: 20,
        starting_balling: 1060,
        final_balling: 1008,
        ibu: 70,
        type: "IPA",
        reviews: [
            {
                rating: 4,
                custom_name: "Pudingfihgter",
                email: "puding@gmail.com",
                comment: "Ammmazing!",
                date: "2025.02.11"
            },
            {
                rating: 2,
                custom_name: "Diabolic light",
                email: "diabolic@gmail.com",
                comment: "Drinkable..",
                date: "2025.04.06"
            }
        ]
    },
    {
        name: "Stoutzilla",
        description: "Description of beer",
        images: ["images/beer.jpg"],
        alcohol: "8%",
        price: 10,
        discount: 0,
        color_scheme: "black",
        batch_number: 1,
        link: "stoutzilla",
        stock: 40,
        starting_balling: 1075,
        final_balling: 1005,
        ibu: 30,
        type: "stout"
    },
    {
        name: "Yabai Yakuza",
        description: "Description of beer",
        images: ["images/beer.jpg"],
        alcohol: "6%",
        price: 10,
        discount: 0,
        color_scheme: "red",
        batch_number: 1,
        link: "yabai_yakuza",
        stock: 30,
        starting_balling: 1055,
        final_balling: 1005,
        ibu: 50,
        type: "IPA"
    },
    {
        name: "Sumo Stout",
        description: "Description of beer",
        images: ["images/beer.jpg"],
        alcohol: "8%",
        price: 10,
        discount: 0,
        color_scheme: "black",
        batch_number: 1,
        link: "sumo_stout",
        stock: 40,
        starting_balling: 1075,
        final_balling: 1005,
        ibu: 20,
        type: "stout"
    },
    {
        name: "Hop Samurai",
        description: "Description of beer",
        images: ["images/beer.jpg"],
        alcohol: "7%",
        price: 10,
        discount: 0,
        color_scheme: "green",
        batch_number: 1,
        link: "hop_samurai",
        stock: 40,
        starting_balling: 1075,
        final_balling: 1005,
        ibu: 60,
        type: "IPA"
    },
    {
        name: "Hopkido",
        description: "Description of beer",
        images: ["images/beer.jpg"],
        alcohol: "6%",
        price: 10,
        discount: 0,
        color_scheme: "green",
        batch_number: 1,
        link: "hopkido",
        stock: 60,
        starting_balling: 1075,
        final_balling: 1005,
        ibu: 65,
        type: "IPA"
    }
]